text= input("Enter text to write to the file: ")
file=("output.txt", "w")
file.write(text+"\n")
file.close()
print("Written successfully.")
extra= input("Enter text to append: ")
file=("output.txt", "a")
file.write(extra+"\n")
file.close()
print("Appended successfully.")
f= open("output.txt", "r")
print("Final content of file:")
print(f.read())
f.close()
    